In \[2\]:

    import numpy as np

In \[3\]:

    sample_list=(6,7,9)
    np.array(sample_list)

Out\[3\]:

    array([6, 7, 9])

In \[4\]:

    arr=np.array([1,2,3])
    arr

Out\[4\]:

    array([1, 2, 3])

In \[5\]:

    list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
    np.array(list_of_lists)

Out\[5\]:

    array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

In \[7\]:

    arr=np.array([1,2,3])
    arr

Out\[7\]:

    array([1, 2, 3])

In \[9\]:

    arr=np.array([[1,2,3],[4,5,6]])
    arr

Out\[9\]:

    array([[1, 2, 3],
           [4, 5, 6]])

In \[10\]:

    arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
    arr

Out\[10\]:

    array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

In \[11\]:

    np.arange(2,100)

Out\[11\]:

    array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
           19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
           36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
           53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
           70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
           87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In \[12\]:

    np.arange(5,35,6)

Out\[12\]:

    array([ 5, 11, 17, 23, 29])

In \[13\]:

    np.zeros(6)

Out\[13\]:

    array([0., 0., 0., 0., 0., 0.])

In \[16\]:

    np.ones(6,dtype=int)

Out\[16\]:

    array([1, 1, 1, 1, 1, 1])

In \[17\]:

    np.ones((2,5),dtype=int)

Out\[17\]:

    array([[1, 1, 1, 1, 1],
           [1, 1, 1, 1, 1]])

In \[18\]:

    np.linspace(0,20,10)

Out\[18\]:

    array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
           11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In \[19\]:

    np.linspace(0,10,15)

Out\[19\]:

    array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
            3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
            7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In \[20\]:

    np.eye(5,dtype=int) ###identity matrix

Out\[20\]:

    array([[1, 0, 0, 0, 0],
           [0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0],
           [0, 0, 0, 0, 1]])

In \[21\]:

    np.random.rand(2,4)

Out\[21\]:

    array([[0.43213239, 0.87148644, 0.40488717, 0.34312145],
           [0.98539493, 0.97103094, 0.68074656, 0.06459375]])

In \[22\]:

    np.random.randn(2,5)

Out\[22\]:

    array([[-0.60309765, -1.93078789,  0.00193666,  0.36666309, -0.73313156],
           [-0.2121596 , -1.74549432, -0.42286733,  0.87420878,  0.799601  ]])

In \[23\]:

    np.random.randint(0,10,15)

Out\[23\]:

    array([2, 7, 9, 5, 8, 5, 7, 6, 0, 5, 1, 5, 2, 3, 9])

In \[24\]:

    np.random.randint(10,100,15)

Out\[24\]:

    array([79, 25, 18, 87, 17, 72, 61, 87, 91, 44, 18, 48, 45, 50, 94])

In \[25\]:

    np.random.randint(20,56,100)

Out\[25\]:

    array([29, 33, 33, 20, 44, 21, 37, 46, 21, 48, 33, 45, 30, 51, 36, 49, 20,
           41, 40, 33, 46, 31, 20, 35, 51, 25, 30, 29, 53, 21, 36, 52, 29, 28,
           35, 47, 28, 45, 23, 28, 44, 39, 26, 50, 34, 39, 36, 55, 22, 20, 34,
           55, 25, 28, 37, 27, 47, 32, 39, 47, 39, 30, 49, 48, 54, 34, 21, 20,
           20, 53, 38, 37, 52, 27, 44, 50, 22, 27, 20, 54, 45, 37, 37, 53, 33,
           32, 32, 54, 27, 46, 40, 46, 36, 25, 51, 54, 42, 24, 32, 32])

In \[26\]:

    sample_array=np.arange(2,20)
    sample_array

Out\[26\]:

    array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
           19])

In \[27\]:

    rand_array=np.random.randint(0,10,15)
    rand_array

Out\[27\]:

    array([0, 3, 4, 2, 0, 9, 8, 5, 5, 6, 9, 1, 7, 1, 4])

In \[28\]:

    sample_array.min()

Out\[28\]:

    2

In \[29\]:

    sample_array.argmin()

Out\[29\]:

    0

In \[30\]:

    rand_array.argmin()

Out\[30\]:

    0

In \[31\]:

    rand_array.max()

Out\[31\]:

    9

In \[32\]:

    rand_array.argmax()

Out\[32\]:

    5

In \[33\]:

    sample_array.argmax()

Out\[33\]:

    17

In \[34\]:

    sample_array.dtype

Out\[34\]:

    dtype('int32')

In \[36\]:

    a=np.eye(5)
    a

Out\[36\]:

    array([[1., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0.],
           [0., 0., 1., 0., 0.],
           [0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 1.]])

In \[37\]:

    a=np.random.rand(2,3)
    a

Out\[37\]:

    array([[0.19936711, 0.02771039, 0.76250978],
           [0.56254424, 0.37949291, 0.73951878]])

In \[38\]:

    a.T

Out\[38\]:

    array([[0.19936711, 0.56254424],
           [0.02771039, 0.37949291],
           [0.76250978, 0.73951878]])

In \[39\]:

    sample_array=np.arange(10,28)
    sample_array

Out\[39\]:

    array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
           27])

In \[40\]:

    sample_array=sample_array.reshape(6,3)
    sample_array

Out\[40\]:

    array([[10, 11, 12],
           [13, 14, 15],
           [16, 17, 18],
           [19, 20, 21],
           [22, 23, 24],
           [25, 26, 27]])

In \[41\]:

    sample_array=sample_array.reshape(3,4)
    sample_array

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-41-8ea8b3d72c0b> in <module>
    ----> 1 sample_array=sample_array.reshape(3,4)
          2 sample_array

    ValueError: cannot reshape array of size 18 into shape (3,4)

In \[42\]:

    sample_array[5]=100
    sample_array

Out\[42\]:

    array([[ 10,  11,  12],
           [ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24],
           [100, 100, 100]])

In \[43\]:

    sample_array=np.arange(10,100)
    sample_array

Out\[43\]:

    array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
           27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
           44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
           61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
           78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
           95, 96, 97, 98, 99])

In \[44\]:

    sample_array[1:12]

Out\[44\]:

    array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In \[45\]:

    subset_sample_array=sample_array[0:7]
    subset_sample_array

Out\[45\]:

    array([10, 11, 12, 13, 14, 15, 16])

In \[46\]:

    sample_array[:]=1001
    sample_array

Out\[46\]:

    array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
           1001, 1001])

In \[47\]:

    ##Two dimensional array

In \[48\]:

    sample_matrix=np.array([[24,13,2,15],[15,2,54,65],[56,76,24,7]])
    sample_matrix

Out\[48\]:

    array([[24, 13,  2, 15],
           [15,  2, 54, 65],
           [56, 76, 24,  7]])

In \[49\]:

    sample_matrix[2][2]

Out\[49\]:

    24

In \[50\]:

    sample_matrix[1][2]

Out\[50\]:

    54

In \[51\]:

    sample_matrix[:,2]

Out\[51\]:

    array([ 2, 54, 24])

In \[52\]:

    sample_matrix[1,1]

Out\[52\]:

    2

In \[53\]:

    sample_matrix[1:3,2:4]

Out\[53\]:

    array([[54, 65],
           [24,  7]])

In \[54\]:

    sample_matrix[1:,2:]

Out\[54\]:

    array([[54, 65],
           [24,  7]])

In \[55\]:

    sample_matrix[2]

Out\[55\]:

    array([56, 76, 24,  7])

In \[56\]:

    sample_array=np.arange(1,31)
    sample_array

Out\[56\]:

    array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
           18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])