In [7]:
import numpy as np

In [8]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [9]:
np.max(sample_array)

30

In [11]:
np.min(sample_array)

1

In [12]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [13]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [14]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [15]:
np.argmax(sample_array)

29

In [16]:
np.argmin(sample_array)

0

In [17]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [18]:
np.std(sample_array)

8.65544144839919

In [19]:
np.var(sample_array)

74.91666666666667

In [20]:
np.mean(sample_array)

15.5

In [22]:
array=np.random.randn(3,4) ##normal distribution
array

array([[ 1.20554767, -0.39290945,  0.05931266,  1.28820645],
       [-1.07002651,  0.18302243,  0.1009679 ,  0.25718234],
       [ 0.14057617, -0.27152307, -0.01665825, -0.36581424]])

In [23]:
np.round(array,decimals=3)

array([[ 1.206, -0.393,  0.059,  1.288],
       [-1.07 ,  0.183,  0.101,  0.257],
       [ 0.141, -0.272, -0.017, -0.366]])